### ISSUE TITLE
Deployed lambdas have a `.build` prefix in the handler path

### ISSUE THREAD

**Issue by lucaspiller** [serverless/serverless-plugin-typescript#268]
I've got a weird issue: When new Lambdas are created, the handler path is prefixed with `.build`. There is no `.build` folder in the uploaded zip though, so when the Lambda is ran, it results in an error:

```
{
  "errorType": "Runtime.HandlerNotFound",
  "errorMessage": ".build/src/handlers/<snip>/index.handler is undefined or not exported",
  "stack": [
    "Runtime.HandlerNotFound: .build/src/handlers/<snip>/index.handler is undefined or not exported",
    " at Object.module.exports.load (/var/runtime/UserFunction.js:246:11)",
    " at Object.<anonymous> (/var/runtime/index.js:43:30)",
    " at Module._compile (internal/modules/cjs/loader.js:1085:14)",
    " at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
    " at Module.load (internal/modules/cjs/loader.js:950:32)",
    " at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
    " at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
    " at internal/main/run_main_module.js:17:47"
  ]
}
```

![Screenshot 2022-03-22 at 16 34 09](https://user-images.githubusercontent.com/18404/159506744-fb1939ed-d584-40a5-b300-f7b1e9519f58.png)

![Screenshot 2022-03-22 at 16 31 24](https://user-images.githubusercontent.com/18404/159506016-4febba8a-5442-403c-b582-6d45a19766e6.png)

If I remove the `.build` prefix on the AWS console everything works perfectly, and if I redeploy it doesn't revert it back.

Any ideas what happened here? 

Versions:

- serverless 3.3.0
- serverless-plugin-typescript 2.1.1
- typescript 4.5.5

**Comment by lucaspiller** [comment]
I dug into the code, and it's actually caused by [serverless-plugin-localstack](https://github.com/localstack/serverless-localstack/issues/168) which doesn't work with this plugin.
